### ISSUE TITLE
After update Bluetooth dosen't working

### ISSUE THREAD

**Issue by Wiciu08** [Exynoobs/android_device_samsung_exynos9810-common#2]
After update(in change list there is bluetooth are fixed) bluetooth don't working, after connect to bluetooth device sound came from device not headphones, after change device to listen from headphones nothing changes, sound play from device not bluetooth device, there is solution for this or that is a rom problem?

**Comment by grip2s** [comment]
But when somebody call me i can hear him on bluetooth headphones but music plays from device not headphones

**Comment by josip-k** [comment]
Its resolved, will be a part of next release.
